### ISSUE TITLE
Error when staring up app/__init.py

### ISSUE THREAD

**Issue by StudentDX** [PrathamRawat/phive#2]
This error pops up when starting __init__.py, running in an Ubuntu virtual box.
`
Traceback (most recent call last):
  File "app/__init__.py", line 2, in <module>
    from app.utl.matrix import Matrix
ModuleNotFoundError: No module named 'app'
`
I had this problem last project, and the problems appears to be in the imports with "app."
Currently, removed "app." in __init__.py in branch 'UI,' like so:
`
from app.utl.matrix import Matrix
from app.data.data import *
`

**Comment by StudentDX** [comment]
New issue encountered
```
Traceback (most recent call last):
  File "__init__.py", line 55, in <module>
    @login_required
  File "__init__.py", line 10, in login_required
    @wraps(f)
NameError: name 'wraps' is not defined
```
Pulled from master after recent update by junhee

**Comment by Lee-Junhee** [comment]
probably should open a new issue for the decorator

**Comment by Lee-Junhee** [comment]
it boots now as of the latest commit, solved by removing the "app."
